version: '3'
services:
  ansible:
    container_name: 'ansible'
    image: 'ansible:5'
    build:
      context: '.'

    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './ansible:/srv/ansible:rw'

    hostname: 'ansible.container'
    networks:
      - 'vlan'
  
networks:
  vlan:
